### ISSUE TITLE
Integrate Arbitrum to Giveth DApp

### ISSUE THREAD

**Issue by MoeNick** [Giveth/Roadmap#100]
We won the Grant So we need to integrate the network into teh DApp
https://questbook.app/dashboard/?grantId=0x4494cf7375aa61c9a483259737c14b3dba6c04e6&chainId=10&proposalId=0x626

**Comment by jainkrati** [comment]
@MoeNick is this for Pairwise or Giveth?

**Comment by MoeNick** [comment]
This is for Giveth. We won the grant. I will provide all FrontEnd and the backend issues probably today
