### ISSUE TITLE
ENS QF Round

### ISSUE THREAD

**Issue by MoeNick** [Giveth/Roadmap#102]

**Comment by laurenluz** [comment]
thanks MoeNick! I think this epic really only has 1 issue :)

**Comment by laurenluz** [comment]
@koday1 can you create and issue and add it to this epic for adding the tx info to the backend... this is blocked ofc, by data analysis, but we can put it in here to set up.

**Comment by koday1** [comment]
@laurenluz created the issue here: https://github.com/Giveth/giveth-dapps-v2/issues/4018
