### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by MoeNick** [Giveth/Roadmap#13]

**Comment by mosaeedi** [comment]
To have the latest copy for all notifications, please take a look at this file.
[Google sheet](https://docs.google.com/spreadsheets/d/1VMsmF9oJEwf1JyNEAfWi2n2eYvG6ZtnkXKB_3Hv29x8/edit#gid=0)


Also, you can see the exact icon for all of the notifications here
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12194%3A227334)


---

General rules:

1. all copies that will be replaced inside **{ , }** should use **body/B** font family
2. only these should change into link style (also staying bold)
- {poolname} 
- {project name}
- {tx link}
- {Click here}

---


please take a look at the notification structure here
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12068%3A210172)

**Comment by MoeNick** [comment]
@MohammadPCh @RamRamez @CarlosQ96 @mohammadranjbarz the final notification list and templates are above.
