### ISSUE TITLE
Revoke the first badge of the projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/Roadmap#22]

**Comment by CarlosQ96** [comment]
While I moved all to unit testing, and events arrive from my tests. Sometimes they don't
I talked to Mohammad about rewriting segment library to avoid using their inmemory queue and instead we do it with Bull.
I started on this.

**Comment by MoeNick** [comment]
Issue moved to [Giveth/impact-graph #665](https://github.com/Giveth/impact-graph/issues/665) via [**Zenhub**](https://www.zenhub.com/)
