### ISSUE TITLE
Integrate WebLate for dynamic translations on the repo

### ISSUE THREAD

**Issue by mateodaza** [Giveth/Roadmap#37]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18689480/198813904-0fa88178-9e63-4597-bf3c-26be40b4bfbb.png">

After completing 100% english dictionary we need to communicate with WebLate and update the translations whenever we desire or when collaborators update/improve translations.

There are ways to handle PRs and commits from their repo

**Comment by MoeNick** [comment]
can you share this with us man? :)

**Comment by mateodaza** [comment]
> can you share this with us man? :)

yes! I showed @RamRamez and the whole spanish translation team, it's not completely necessary for all devs to know it but we can have a session
