### ISSUE TITLE
Giveth Analytics Dashboard

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#42]
Original Issue started by @spectoregia 

Creating a dashboard to have all the giveth stats, info and data retrievable/viewable 

will combine financial stats, dao stats and donation stats into a single website. 

Hopefully this becomes the definitive dashboard for tracking giveth data for non-devs
current prototype is here:
https://analytics-dashboard-blue.vercel.app/

I would like to wrap up this dashboard to capture info proposed here as well:
https://forum.giveth.io/t/should-we-begin-publishing-quarterly-dao-stats/865

**Comment by spectoregia** [comment]
Big thanks to @RamRamez for creating https://analytics-dashboard-blue.vercel.app/  
The structure and metrics are great and no further comments there.
The only issue which I suspect might not be 100% correct is the data itself. I can see total donations USD 1,449,928 which I think it's too low. probably missing at least 1-2mil. (date range I selected: Oct 2021 - today). I am not sure with whom we can proof check the numbers and confirm the data source but it's certainly needed before we can close it.

**Comment by divine-comedian** [comment]
> Big thanks to @RamRamez for creating https://analytics-dashboard-blue.vercel.app/ The structure and metrics are great and no further comments there. The only issue which I suspect might not be 100% correct is the data itself. I can see total donations USD 1,449,928 which I think it's too low. probably missing at least 1-2mil. (date range I selected: Oct 2021 - today). I am not sure with whom we can proof check the numbers and confirm the data source but it's certainly needed before we can close it.

I think @CarlosQ96 was working with Ramin to get the backend data

**Comment by CarlosQ96** [comment]
I can check the data with you @spectoregia, I feel we got 3 different sources of information, and I wanna check the validity of said data.
As far as the info in @RamRamez dashboard, they are fetched directly from our main database. I think I have to tweak a query a bit, that I saw a small issue on one of them. But the main db should have all the truth always.

But we should validate, maybe I have to change the queries a bit. There are things I exclude like failed donations and also trace donations are not part of it either.

**Comment by ahmadabugosh** [comment]
Hey also I wanted to add that we also have Google Analytics setup, which can tell us platform data, such as:

- Sources of traffic (Twitter, Email, Direct etc.)
- Number of new versus recurring users
- Popularity of pages, how many views (including project pages, GIVfarms etc.)
- Number of donations and projects created (along with their traffic sources)
- Conversion rate of donations (how many people visited donation pages, versus actually donated)

It has an API, so we could pull all that data into whatever platform you're building

**Comment by spectoregia** [comment]
it appears https://analytics-dashboard-blue.vercel.app/ data is accurate and working fine now!

As a next step, we need to correct the duplicicity issue on the category count. After discussing it with MoeNick we arrived to the solution to simply normalize the category identifiers and present them in 100% stacked bars.

Also, having a visual presentation for the data in the app was something we discussed with Ramin and can also be treated as the 2nd next step.

**Comment by RamRamez** [comment]
> it appears https://analytics-dashboard-blue.vercel.app/ data is accurate and working fine now!
> 
> As a next step, we need to correct the duplicicity issue on the category count. After discussing it with MoeNick we arrived to the solution to simply normalize the category identifiers and present them in 100% stacked bars.
> 
> Also, having a visual presentation for the data in the app was something we discussed with Ramin and can also be treated as the 2nd next step.

For the duplicity issue, I normalized category donation values. Besides that, I added a pie chart for a better presentation. It's deployed.
https://analytics-dashboard-blue.vercel.app/

**Comment by spectoregia** [comment]
Thanks @RamRamez !! Can we also add monthly bar charts for Projects Count, Donors Count and Total Donations USD?

Small feedback, can we format the Total Donations USD as number so there is a comma-separated formatting for easier reading of the numbers. i.e. 1,455,000. right now it just shows 1455000

**Comment by RamRamez** [comment]
> Thanks @RamRamez !! Can we also add monthly bar charts for Projects Count, Donors Count and Total Donations USD?
> 
> Small feedback, can we format the Total Donations USD as number so there is a comma-separated formatting for easier reading of the numbers. i.e. 1,455,000. right now it just shows 1455000

I added thousands separator for easier reading.
Right now backend API returns the total value on each endpoint. I talked with @CarlosQ96 to add an array containing monthly data as output. He is working on it.

**Comment by spectoregia** [comment]
Thanks @RamRamez !!
I got a small feedback from Ahsley regarding the presentation of the data - can we add a small note under the main categories explaining what they are? 

Something like this:
Projects count
(total number of new projects onboarded during the selected timeframe)
 
Donors count
(total number of unique donors during the selected timeframe )

**Comment by spectoregia** [comment]
and 2nd point - are we ready to progress with the Giveth Trace data and also include them in the count of this dashboard?

**Comment by RamRamez** [comment]
> Thanks @RamRamez !! I got a small feedback from Ahsley regarding the presentation of the data - can we add a small note under the main categories explaining what they are?
> 
> Something like this: Projects count (total number of new projects onboarded during the selected timeframe)
> 
> Donors count (total number of unique donors during the selected timeframe )

I added a tooltip for each query.

**Comment by RamRamez** [comment]
> and 2nd point - are we ready to progress with the Giveth Trace data and also include them in the count of this dashboard?

I'm busy with some giveth.io bugs at the moment. I'll add them soon.

**Comment by RamRamez** [comment]
> Thanks @RamRamez !! Can we also add monthly bar charts for Projects Count, Donors Count and Total Donations USD?
> 
> Small feedback, can we format the Total Donations USD as number so there is a comma-separated formatting for easier reading of the numbers. i.e. 1,455,000. right now it just shows 1455000

I added a column chart for each query of the dashboard. It's live.

Praise @CarlosQ96 for adding monthly data to queries so fast.

**Comment by spectoregia** [comment]
@RamRamez I would like to request one additional metric to be added to our dashboard: total number of donations (qty) 
Thanks!

**Comment by RamRamez** [comment]
> @RamRamez I would like to request one additional metric to be added to our dashboard: total number of donations (qty) Thanks!

Sure. I talked with @CarlosQ96, and we don't have this endpoint right now. @CarlosQ96 will develop it and I will develop the UI.
Just so you know, we are swamped working on the new homepage design and we are supposed to deliver it next week. So if this is not urgent, we will start working on it after the new homepage is live.

**Comment by spectoregia** [comment]
@RamRamez sure thing! you can prioritize it as you think it makes sense. 
In the meantime, can I get the raw data to update our slide deck with the recent information? maybe @mohammadranjbarz could help with this since he already provided the data in raw format before with me once... 
thank you!

**Comment by RamRamez** [comment]
@spectoregia total number of donations is up on the dashboard and you can test it.

We can assign a domain name under giveth.io for this dashboard, like stats.giveth.io or analytics.giveth.io
@spectoregia @divine-comedian WDYT?

**Comment by divine-comedian** [comment]
> @spectoregia total number of donations is up on the dashboard and you can test it.
> 
> We can assign a domain name under giveth.io for this dashboard, like stats.giveth.io or analytics.giveth.io @spectoregia @divine-comedian WDYT?

`stats.giveth.io` seems good - short and simple

**Comment by spectoregia** [comment]
Thanks @RamRamez looks great!
Agreed with @divine-comedian on the URL

**Comment by RamRamez** [comment]
> > @spectoregia total number of donations is up on the dashboard and you can test it.
> > We can assign a domain name under giveth.io for this dashboard, like stats.giveth.io or analytics.giveth.io @spectoregia @divine-comedian WDYT?
> 
> `stats.giveth.io` seems good - short and simple

`stats.giveth.io` is up.
