### ISSUE TITLE
Project Activity Feed (Updates)

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/Roadmap#43]
Have a specified place where we show a feed of the most recent project updates.

This place could be a section here labelled "Activity"

![image](https://user-images.githubusercontent.com/74267818/202526146-935872a1-03b5-4656-a7bd-5d8b0d3dac3d.png)

Or we could have aspecific spot on the projects page where we feature the lastest updates from projects.

This will provide value to the application and community in the following ways:

- Donors can keep up with the latest activity from projects which will provide opportunity for stronger storytelling and connection between donors and projects
- Encourage projects to stay active and provide regular updates

**Comment by spectoregia** [comment]
+1 to this from me. I have always had trouble with finding the most recently updated/added projects.
maybe another suggestion if it makes sense: to also add a possibility of sorting option on the projects page: sort by: latest added, most popular, etc.

**Comment by MoeNick** [comment]
@Tosinolawale @mosaeedi it needs your attention.

**Comment by CarlosQ96** [comment]
I think depending on the design. Somethings can change. So which filters are we adding to this new view? 

I created this Pr https://github.com/Giveth/impact-graph/pull/752  that orders by createdAt by default, and you can filter by projectId, it's paginated.

I like @spectoregia mostLiked filter. I could add that, but ultimately design sets the filters. So before merging lets decide that @MoeNick. But the Pr with listing ordered by creationDate is ready.

**Comment by MoeNick** [comment]
the home page is updated with the ticker of the last project update and featured updates by Admins. 
If you find some awesome projects update you can send them us.
