### ISSUE TITLE
Project Refactoring & Updated Project Pages

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/Roadmap#44]
Hey team, we want to update our project pages to include more information, like social links (website, twitter, etc), an image and video gallery, location data, impact data (what $ amount correlates to what social impact) and funding goals (see [this issue](https://github.com/Giveth/giveth-dapps-v2/issues/1374) for a discussion on this topic).

This would also support us to create other features like [interactive maps](https://docs.google.com/document/d/1oYGyOo6ZzTj0JTrddj0j8sjptaQUblJaRbtcE34kmZI/edit#)

**Comment by MoeNick** [comment]
https://forum.giveth.io/t/improving-single-project-screen/983
we now have the prototype, I hope we can start based on this design.
