### ISSUE TITLE
Conduct GIVfi User Research

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#57]
Better late than never. Draft and post some short-form questions and multiple choice questions in a short typeform. Can be compiled into a typeform on Discord and also some multiple-choice polls via Twitter. 

We reviewed and drafted some question on our latest GIVfi call, this is the first draft I tidied up after our meeting:

https://docs.google.com/document/d/18TeTvO_9qWBcUYwllG1IVy6X2TkpegNT8_Zu3dP4zrQ/edit?usp=sharing

**Comment by divine-comedian** [comment]
@c0ric0ri @laurenluz @GriffGreen @SnakeGH 

I would love your input on the format and wording of the questions. Give it a quick :eyes: when you can please. 

Also for the comms folk, pick out the ones you think are suitable for Twitter and make any adjustments separately if you need.

**Comment by SnakeGH** [comment]
Looks amazing @divine-comedian and I think you have covered all the questions. I make some light sentence structure suggestions, but @danelsuga will be better to cover true grammatics. 

otherwise, I really look forward to seeing what @Cotabe  & Lauren suggest :)

**Comment by danelsuga** [comment]
I left some comments.

**Comment by laurenluz** [comment]
I think these are great @divine-comedian - I added some relatively minor comments. When you're happy with it, just tag me again on here and I can start putting some of the questions up as twitter polls next week.

**Comment by divine-comedian** [comment]
> I think these are great @divine-comedian - I added some relatively minor comments. When you're happy with it, just tag me again on here and I can start putting some of the questions up as twitter polls next week.

I'm pretty happy with them, thanks for the review - good to go for Twitter!

**Comment by laurenluz** [comment]
I'll try to post all the links as I put them up for referece.

"What minimum APY" https://twitter.com/Giveth/status/1642878968163385349

**Comment by c0ric0ri** [comment]
Left some copy tweaks on the word doc to clarify the first page. There's also a period or 2 missing on the typeform, small stuff.

Posting the form here for reference: https://giveth.typeform.com/givsavings

@divine-comedian can you move this issue to the planning board please, and set the status to Review/QA?

**Comment by c0ric0ri** [comment]
@laurenluz just to be clear are you writing tweets for this then or should I create a separate issue?

**Comment by divine-comedian** [comment]
> Left some copy tweaks on the word doc to clarify the first page. There's also a period or 2 missing on the typeform, small stuff.
> 
> Posting the form here for reference: https://giveth.typeform.com/givsavings
> 
> @divine-comedian can you move this issue to the planning board please, and set the status to Review/QA?

A few people already reviewed it including Lauren, Suga, Jake and yourself

I'd like to keep it within the GIVfi epic where it is - just looping you in so you know that this is happening 

To your comment above I think Lauren already began cherry picking some questions and posting them on Twitter.
https://twitter.com/Giveth/status/1642878968163385349

**Comment by laurenluz** [comment]
"what chain" https://twitter.com/Giveth/status/1643272268364013569

**Comment by laurenluz** [comment]
"what % fee" https://twitter.com/Giveth/status/1643680455181635584

**Comment by laurenluz** [comment]
"what USD would you deposit" https://twitter.com/Giveth/status/1643709197102587908

**Comment by divine-comedian** [comment]
Collecting typeform responses here:
https://docs.google.com/spreadsheets/d/1uT8yldn5eRN5zVbZJVkkDZop0wVzBThKCIHgBbCDlAA/edit?usp=sharing

**Comment by laurenluz** [comment]
"What token" https://twitter.com/Giveth/status/1644020368280002569

**Comment by divine-comedian** [comment]
FYI @Tosinolawale  here!!

**Comment by divine-comedian** [comment]
FYI We finished the Research and review it on the call a few weeks ago. The major conclusion is that we should start with an ETH Vault not on mainnet - almost certainly we will find a vault/protocol on Optimism that will fit our bill.
