### ISSUE TITLE
Move the main app to run on Kubernetes

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/Roadmap#58]
This issue has been long standing, but does not seem to get the priority it really needs. I do get that people like flashy new functionality, but I assure you all we are building will need to scale one day (or go down). We want to do it now and not wait for later. The migration is getting harder and harder because features are being layered on top of an already expansive system.

**Please prioritize this issue!!**

**Comment by aminlatifi** [comment]
@geleeroyale Thanks for creating this. In our last call, it was mentioned that impact-graph is not horizontally scalable and I agree. But do you think it's a blocker? We can migrate it to k8s still but don't use the scaling feature for it yet.

**Comment by geleeroyale** [comment]
@mhmdksh is our expert here and more adequately prepared to explain why it is necessary to modify the existing deployment even without scaling.

**Comment by laurenluz** [comment]
MoeShehab provided a doc on how to move forward
Amin (in dev call) - MoeShehab has documented it, next step is to onboard devs to use Kubernetes to work w/ it, currently we need to deploy & restart services... we do it manually.

Kubernetes bundle on staging is working well
We should set up a couple of sessions to onboard @mohammadranjbarz @CarlosQ96 @aminlatifi

**Comment by laurenluz** [comment]
@MoeNick will set up a meeting w/ @mhmdksh

**Comment by mhmdksh** [comment]
Hey guys, I'm adding the list of current issues for convenience:
 
https://github.com/Giveth/impact-graph/issues/648
https://github.com/Giveth/impact-graph/issues/609
https://github.com/Giveth/devops/issues/89
https://github.com/Giveth/devops/issues/80
https://github.com/Giveth/devops/issues/106
https://github.com/Giveth/impact-graph/issues/712
https://github.com/Giveth/notification-center/issues/11
https://github.com/Giveth/SiweAuthMicroservice/issues/9
https://github.com/Giveth/apiGive/issues/14
https://github.com/Giveth/devops/issues/100
https://github.com/Giveth/devops/issues/103

Link to the Article: https://www.notion.so/giveth/The-Road-To-Kubernetes-a600ad1753ce4c72999a287c2ccc8041?pvs=4

Staging ENV running on Kubernetes is: https://staging.k8s.giveth.io
