### ISSUE TITLE
Fix listing problems for sharing project updates

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/Roadmap#6]
**Problem:** Right now, when users share an update we unlist the project itself until we review the update and then list the project again!

It's not a good UX, and also each time users share an update the project will be unlisted which can be annoying for the project owner and somehow prevent users from sharing future updates!

**Solution:** when the user shares an update, only the new update should be unlisted and hidden until we review the update and publish it. we should not change the project status because of a project update.
Also when users sent the update we have to let them know the update will be published when it's reviewed!

**Comment by divine-comedian** [comment]
An idea from:
https://forum.giveth.io/t/mandatory-updates-for-verified-projects/723/2

## Optimistic Update Moderation

Perhaps we build some sort of optimistic update moderation, where we assume all project updates are well intentioned, removing the requirement for individual review/approval and have an open signalling system for users.

Each project update, once posted could have three options under the heading "How informative was this update?", users, other than the project owner, can respond with "upvote","downvote" or flag/report. 

We can go further and set metrics to keep project moderators informed with minimal overhead. We could say that if a project update has over 75% downvotes with a minimum votes of 5 then a flag is sent to the project verification team, if a user flags or reports then obviously a flag is sent as well.

 If the update is malicious or breaks our terms and conditions we de-list or cancel it. If its a bad/uninformative update we send them an email.

If a project games the system and provides garbage updates and/or "upvotes" themselves via multiple accounts it really doesn't provide any clear benefits for them. Other users can see the project posting uninformative/bad updates and using their discretion, will simply not donate funds. 

Going further, if we choose to **incorporate project updates into a project ranking system** we could say that any updates above the downvote threshold are disqualified, meaning the project is ranked as if that update never existed. We could also allow project mods to manually disqualify updates as well.

**Comment by MoeNick** [comment]
I think the whole Epic can close because a fix of project updates won't change the listings of projects.
