### ISSUE TITLE
Integrate Gitcoin passport

### ISSUE THREAD

**Issue by laurenluz** [Giveth/Roadmap#66]

**Comment by MoeNick** [comment]
- Change our authentication service with the Passport API,
- fetching the user profile data, save the rank.

**Comment by laurenluz** [comment]
We need to integrate gitcoin passport as a 1st step to quadratic funding.

This docs are here: https://docs.passport.gitcoin.co/building-with-passport/quick-start-guide

Gitcoin passport allows us to use a customizable scoring system (choose which stamps have which value).

I made some notes in this doc: https://docs.google.com/document/d/19hGvi1M2Zmpy-qqe-1cBqk9pGJd9ZTbRJkpFX2Cyd14/edit

Amin says:
- we need to add a new authentication service via gitcoin passport
- option to fetch the user profile from gitcoin passport from impact graph or any other service
- this depends on how we want to use this score
- our backend holds a private key that can access passport score

**Comment by aminlatifi** [comment]
@laurenluz It's better the devops team create passport key for production env

**Comment by laurenluz** [comment]
Converting this issue to an epic w/ some subtasks :) we can continue the discussion in there.
