### ISSUE TITLE
Project X Revamping | Public View

### ISSUE THREAD

**Issue by MoeNick** [Giveth/Roadmap#68]

**Comment by MoeNick** [comment]
@divine-comedian @laurenluz 

Shall I close all revamping single project page and public project page issues? 
if we give up the GIVfi I can't see any benefit without monetizing these features, unless we make sure that discussions are worth it by the the user engagements.

**Comment by divine-comedian** [comment]
I don't think we will work on this one anytime soon- we could close it as not planned

**Comment by laurenluz** [comment]
yeah agree, I don't think we want to work on this any time soon, although I'm not sure we want to close it an lose all the work of creating & scoping out issues. maybe icebox?

**Comment by MoeNick** [comment]
I closed them, some of them were interesting like locations and galleries that are somehow related to Quality issue, maybe we can re-use some of the designs.
