### ISSUE TITLE
Giveth Pro

### ISSUE THREAD

**Issue by laurenluz** [Giveth/Roadmap#76]
Giveth Pro is a feature proposed by @divine-comedian where - in order to gain access to near features like the revamped project single page (and possible entrance to QF rounds) - project owners will need to stake (and lock) GIV.

Here is the [spec](https://www.notion.so/giveth/Giveth-Pro-480b52b11d1547f7a62085e127222f2f) with more details.

**Comment by divine-comedian** [comment]
Following the GIVeconomy call today I went through and fleshed out the spec with a more detailed user flow and a detailed specification for a deposit contract architecture - please browse at your leisure @mosaeedi @aminlatifi 

https://www.notion.so/giveth/Giveth-Pro-480b52b11d1547f7a62085e127222f2f?pvs=4
