### ISSUE TITLE
Tutorial for new Giveth users

### ISSUE THREAD

**Issue by laurenluz** [Giveth/Roadmap#79]
This issue is the result of a nice long chat with OpenAI about GIVpower, and later a conversation with @mosaeedi.

For new users on Giveth, it can be hard to understand what boosting is, what GIVpower is, what GIVbacks is etc. Part of this is our UX (and we're working on improving it), but it would also be nice to have an automated tutorial for people who are connecting their wallets for the 1st time.

Some little popups that bring the user around and show them how to donate, how to create a project, where to get their GIVbacks etc.

**Comment by laurenluz** [comment]
Could use something like https://introjs.com/ to add it

**Comment by ahmadabugosh** [comment]
@laurenluz I added this issue on the tokenlog earlier, maybe we can merge it with this one? https://github.com/Giveth/giveth-dapps-v2/issues/4025
