### ISSUE TITLE
Giveth Pro User Research

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#81]
Let's build some pointed questions we can ask our social media audiences to prioritize features and estimate how much we should charge users for Giveth Pro

**Comment by divine-comedian** [comment]
Here's a first version of a couple questions:
https://www.notion.so/giveth/User-Research-ab9d2a4b645049a2bb73b179b0e07fef?pvs=4

@laurenluz @oyealmond Could you guys give it a look?

**Comment by oyealmond** [comment]
hey @divine-comedian! 

I found the 2 questions for twitter cool! 
Maybe you can start thinking how the name contest will look like?

**Comment by laurenluz** [comment]
left some quick comments in there @divine-comedian 

I'm going to work with chat gpt to also improve upon the questions for twitter, but if you jump in there w/ answers lmk.

Also I will wait until mon/tues to post these questions on twitter to optimize for engagement

**Comment by laurenluz** [comment]
Thanks for your responses! ok now I added some tweet ideas to the bottom - wdyt @divine-comedian ? or @oyealmond ?

if you're cool w/ them I can schedule next week and post the links here.

**Comment by laurenluz** [comment]
tweet 1: https://twitter.com/Giveth/status/1658484705518563342

**Comment by laurenluz** [comment]
tweet 2: https://twitter.com/Giveth/status/1658873950728847362

**Comment by laurenluz** [comment]
tweet 3: https://twitter.com/Giveth/status/1660670338668134400
