### ISSUE TITLE
GIVbacks on Optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/Roadmap#84]
Donations on Optimism should yield GIVbacks on Optimism. We should hold off distributing GIVbacks for optimism donations on gnosis chain, because it's a weird UX, and try to get this out within the next 2 weeks.

**Comment by divine-comedian** [comment]
@MohammadPCh is blocked by the contracts - are they deployed on the test networks? 

They are here - https://www.notion.so/giveth/bc46e165e9b54e3d889087d12fb04401?v=886ba9282edf47eba90542850f430c2c&pvs=4

We do not need staking contract for GIVbacks - that is still coming out for GIVpower.

Here is our subgraph for tokenDistro:
https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-optim-staging

**Comment by divine-comedian** [comment]
GIVpower contract is up on Optimism Goerli !
https://goerli-optimism.etherscan.io/address/0x632ac305ed88817480d12155a7f1244cc182c298

@aminlatifi will need to make modifications to our subgraph 

I've updated the notion doc with all relevant addresses
https://www.notion.so/giveth/bc46e165e9b54e3d889087d12fb04401?v=886ba9282edf47eba90542850f430c2c&pvs=4

@MohammadPCh @laurenluz

**Comment by aminlatifi** [comment]
Left the PR for review https://github.com/Giveth/giveconomy-subgraph/pull/60
 And deployed for test https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-optim-staging?version=pending&selected=logs

**Comment by aminlatifi** [comment]
@divine-comedian @MohammadPCh The new subgraph is pushed and deployed
For Optimism Goerli is ready here
https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-optim-staging

**Comment by aminlatifi** [comment]
> @divine-comedian @MohammadPCh The new subgraph is pushed and deployed For Optimism Goerli is ready here https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-optim-staging

@laurenluz

**Comment by MoeNick** [comment]
Guys this is a RoadMap Epic Issue let's do the discussions on the issues themselves,  like below:
![image](https://github.com/Giveth/Roadmap/assets/80677512/5d71b7b0-23b6-4dff-b87a-c7d49ebbd2db)
