### ISSUE TITLE
Post Launch QF Issues

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#88]
FYI @laurenluz I transferred all issues here that weren't marked as DONE to this new epic from the old epic. 

We can then close the roadmap issue as completed and follow up on your post-launch improvements and fixes here.

**Comment by jainkrati** [comment]
@laurenluz this needs to be done before Metapool round 19th Feb, right? Shoudl we take it as a p1? 

could you also assign a priority label to each issue under this epic? we will pick in that order.

**Comment by laurenluz** [comment]
@jainkrati I added all the priorities. I would definitely say the epic itself is a p1, and ideally, it would be done by Feb 12 when we need to set up the new round (Feb 19 is when the round starts & donations start coming in)

Completing this issues will make the upcoming meta pool round better for both operators & users, and I think we should try to get it done.

Although, even if it is not done by Feb 12... we will still be able to run the round... but it will be slower, more inefficient & there will be other issues that crop up that will be p0 for devs if we don't solve some of these p1s that make it possible for us not to bug devs 😄 

if that makes sense
