### ISSUE TITLE
Campaign and Cause Pages

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/Roadmap#91]
I think it would be great if we could easily create campaign or causes pages that filter multiple projects on a single page. This would help us stay topical, and raise funds for timely causes. 

I would suggest that it would have the following:

- A filter that we can add to projects for that cause. For example, "Giving Tuesday", "Syria Earthquake", "ETHBarcelona" etc. 
- A banner on top along with text (a title and paragraph)
- Stats for that campaign / cause on top of the page. For example, $X raised so far from Y projects.

**Comment by missgene** [comment]
This is a great idea. What should be the title for this page? I'm tagging @surbhiaroraa here 'cause this is going to be a new page and it must also be SEO-optimized. Please tag me how I can help here :)

**Comment by ahmadabugosh** [comment]
Hey @missgene This is more of a feature request for the Giveth roadmap for the devs to work on, I don't know if there is anything right now to work on.

**Comment by MoeNick** [comment]
1) go to the adminJS, 
2) Click on Campaigns > Creat new campaign
3) Select as Manually Selected 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmFxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad0549a73b6791e7a59067d4980e96b2d9ba45ec/image.png)

4) add project slugs manually

5) if you select isFeature it will show up at the home page in FeturedProjects

There is a show more button in that box in home page, if you click on it, you et redirected to the projects page / selected campaign page, you can see the list of all projects that have this campaign badge. 


@NikolaCreatrix and @WhyldWanderer may have the recorded Demo Video of this feature. 

FYI: @divine-comedian

**Comment by WhyldWanderer** [comment]
I think that Ahmad is describing something different than we already have. 
Here's our current set up...

We can chose projects to feature on the homepage here:
![image](https://github.com/Giveth/Roadmap/assets/74267818/8f76c2cb-6e82-41b0-8a45-1d956285d7a2)


We also have the ability to link to somewhere when they click "Explore" and potentially this could link to the projects page filtered by category... however we don't have the capability to create  custom filters on the projects page. We are only able to choose from the existing main categories. There is no way to link by sub-category. Like this: https://giveth.io/projects/community

We could manually filter the projects that are a part of the chosen "cause" and add them each to the homepage campaign. We can add a hashtag and we can also add a few words where it currently says "Newly Verified Projects" however I think our character count is limited. I would recommend not adding more than 15 projects here as it gets a bit congested.

Here is the manual that Mohammad created about how to edit campaigns in adminbro.. it can also be found pinned in the Comms channel on Discord: https://github.com/Giveth/impact-graph/issues/924#issuecomment-1484909378

**Comment by divine-comedian** [comment]
I think for what we want to achieve immediately with promoting certain causes/projects I think this is good enough.
