### ISSUE TITLE
ETC Integration

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/Roadmap#92]
Here is a list of Goals based on the Grant Agreement:

## Allow Donations on Ether Classic Network
- Allow users to connect on ETC network with wallet
- Allow users to select & donate ETC (native token)
- Fetch price of ETC & show on dapp
- Show ETC donations on donations table
- save ETC network configs to dapp
- save ETC donations in database

## GIVbacks on ETC
- Bridge GIV to ETC, 
- deploy TokenDistro to ETC
- find a subgraph alternative that works with ETC
- Add ETC to GIVstream page
- Create ETC multisig to manage GIVbacks 
- Create ETC & GIV LP
- define GIVbacks eligible list 
- allow ERC20 tokens on GIVbacks list to be able to be donated on ETC
- fetch prices for token list
- save ERC20 ETC donations in DB

## Promotion
- Promote launch on community & comms
- Onboard projects to ETH Classic 

Here's the original grant agreement milestones:
![image](https://github.com/Giveth/Roadmap/assets/67759413/ed97d281-9774-4423-b2a3-775895683915)

**Comment by MoeNick** [comment]
I can't add this issue to this epic, but we should also make sure we can do that:
https://github.com/Giveth/devops/issues/156
